config/routes.rb
# frozen_string_literal: true

Pgapi::Engine.routes.draw do
  post '/graphql', to: 'graphql#execute'

  get :api_token, controller: :api
  patch :generate_token, controller: :api
end

app/models/pgapi/application_record.rb
# frozen_string_literal: true

module Pgapi
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/pgapi/api_controller.rb
# frozen_string_literal: true

module Pgapi
  class ApiController < ApplicationController
    #
    # Inherited Resource
    # ---------------------------------------------------------------------------------------
    #
    #
    #
    #

    inherit_resources

    #
    # Filter
    # ---------------------------------------------------------------------------------------
    #
    #
    #
    #

    # before_action :authenticate_user!

    #
    # Instance Methods
    # ---------------------------------------------------------------------------------------
    #
    #
    #
    #

    def api_token
      # render layout: 'application'
    end

    def generate_token
      resource.regenerate_api_token
      redirect_to main_app.account_path
    end

    #
    # Protected Methods
    # ---------------------------------------------------------------------------------------
    #
    #
    #
    #

    protected

    def resource
      @account = current_user
      @account
    end
  end
end

app/controllers/pgapi/application_controller.rb
# frozen_string_literal: true

module Pgapi
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session

    helper Rails.application.routes.url_helpers

    def authenticate_by_api_token!
      authenticate_or_request_with_http_token do |token, _|
        user = User.find_by(api_token: token)
        raise 'InvalidToken' if user.blank?
        sign_in(user)
        user
      end
    end
  end
end

app/controllers/pgapi/graphql_controller.rb
# frozen_string_literal: true

require_dependency 'pgapi/application_controller'

module Pgapi
  class GraphqlController < ApplicationController
    before_action :authenticate_by_api_token!

    def execute
      variables = ensure_hash(params[:variables])
      query = params[:query]
      operation_name = params[:operationName]
      context = {
        # Query context goes here, for example:
        current_user: current_user,
        current_ability: Ability.new(current_user)
      }
      result = PluragraphSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
      render json: result
    end

    private

    # Handle form data, JSON body, or a blank value
    def ensure_hash(ambiguous_param)
      case ambiguous_param
      when String
        if ambiguous_param.present?
          ensure_hash(JSON.parse(ambiguous_param))
        else
          {}
        end
      when Hash, ActionController::Parameters
        ambiguous_param
      when nil
        {}
      else
        raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
      end
    end
  end
end

app/helpers/pgapi/application_helper.rb
# frozen_string_literal: true

module Pgapi
  module ApplicationHelper
  end
end

app/views/layouts/pgapi/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pgapi</title>
  <%= stylesheet_link_tag    "pgapi/application", media: "all" %>
  <%= javascript_include_tag "pgapi/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pgapi/api/api_token.html.erb
<section class="pb-5">
  <div class="card card-header-block">
    <div class="card-body">
      <div class="row">
        <div class="col"><h4 class="card-title">Api Token</h4></div>
        <div class="col-auto text-right"></div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-12">
          <%= resource.api_token %>
          <%= simple_form_for resource, url: generate_token_path, signed: true do |f| %>
            <%= f.button :submit, "Token Generieren", class: "btn btn-primary"  %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</section>